model:
  id: eu-mfa
  mode: buildings
  image: ghcr.io/transience-mic3/eu-mfa@sha256:a96dd9d7e548b4abe7d3992b905bb605fc1a5f9206a7f65e75d497aa29e9268b
  command: [python, eumfa_buildings.py]
  workingDir: /opt/eu-mfa
  outputPath: /opt/eu-mfa/data/baseline_buildings/output
